# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 20:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presnt_api', '0002_auto_20170323_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pid',
            field=models.CharField(default='0000000', max_length=7, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
