# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presnt_api', '0002_remove_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_time_end',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
