# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presnt_api', '0003_userprofile_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pid',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
